[workspace]
members = ["libcudf-sys"]
resolver = "2"

[package]
name = "libcudf-rs"
version = "0.1.0"
edition = "2021"
authors = [
    "notfilippo",
    "gabotechs",
]

[dependencies]
libcudf-sys = { path = "libcudf-sys" }
cxx = "1.0"
